### ISSUE TITLE
Upgrade to Angular 10

### ISSUE THREAD

**Issue by LieselThuriot** [StevenThuriot/DinnerTime#31]
- [x] Create categories inline
- [x] Create menus inline
- [x] fill in the correct ids after creating a new line
- [x] Invite users inline
- [x] Transfer leadership without a dialog or try to figure out why PrimeNG 10 is causing a navigation on `dialogreference.close();`
- [x] Add floatlabels to input fields

**Comment by StevenThuriot** [comment]
TODO:
- [ ] Invite categories inline
- [ ] Create menus inline
- [ ] Invite users inline
- [ ] Transfer leadership

**Comment by LieselThuriot** [comment]
If anyone wonders, defining the buttons as `pButton` inside a dialog with a form is not enough, you have to add `type='button'` so it won't trigger some random navigation. That being said, it does look a lot better creating new lines inside the grid.

**Comment by LieselThuriot** [comment]
~~🚫 Currently blocked: Waiting for primeng to release final 10.0~~
